backend:
  name: git-gateway

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    description: >
      These are all the standard pages of the website.
    editor:
      preview: false
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "index" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Main Image", name: "image", widget: "image" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/accepting.md"
        label: "Accepting"
        name: "accepting"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Main Image", name: "image", widget: "image" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/i-think-my-son-daughter-is-gay.md"
        label: "I Think My Son / Daughter is Gay"
        name: "i-think-my-son-daughter-is-gay"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Main Image", name: "image", widget: "image" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/my-son-daugher-has-just-come-out.md"
        label: "My Son / Daugher Has Just Come Out"
        name: "my-son-daugher-has-just-come-out"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Main Image", name: "image", widget: "image" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/stories.md"
        label: "Stories"
        name: "stories"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Main Image", name: "image", widget: "image" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/meetings.md"
        label: "Meetings"
        name: "meetings"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Main Image", name: "image", widget: "image" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/links.md"
        label: "Links"
        name: "links"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Main Image", name: "image", widget: "image" }
          - { label: "Body", name: "body", widget: "markdown" }
